import { CasDonneur } from './types';

export const casDonneurs: CasDonneur[] = [
  {
    id: 'cas-1',
    nom: 'Cas 1 — Donneur standard',
    description: 'Situation rassurante conduisant à la libération de la poche.',
    donneur: {
      identifiant: 'DNR-001',
      age: 34,
      sexe: 'Homme',
      region: 'Abidjan',
      typeDonneur: 'Donneur régulier',
      nombreDonsAnterieurs: 8,
      dernierDonLabel: 'Il y a 6 mois',
      dernierDonPlus24Mois: false,
      voyageRecent: false,
      voyageRecentDetail: '',
      antecedentMedical: false,
      antecedentMedicalDetail: '',
      comportementRisque: 'Non',
      profession: 'Enseignant',
    },
    biologie: {
      vih: 'Négatif',
      hbsAg: 'Négatif',
      antiHbc: 'Négatif',
      vhc: 'Négatif',
      syphilis: 'Négatif',
      alt: 28,
      hemoglobine: 14.2,
      natRealise: false,
    },
  },
  {
    id: 'cas-2',
    nom: 'Cas 2 — Risque intermédiaire',
    description: 'Le système recommande un test complémentaire (NAT VHB) avant décision.',
    donneur: {
      identifiant: 'DNR-002',
      age: 24,
      sexe: 'Femme',
      region: 'Bouaké',
      typeDonneur: 'Premier don',
      nombreDonsAnterieurs: 0,
      dernierDonLabel: 'Non applicable (premier don)',
      dernierDonPlus24Mois: false,
      voyageRecent: true,
      voyageRecentDetail: "Retour récent d'une zone à risque infectieux",
      antecedentMedical: false,
      antecedentMedicalDetail: '',
      comportementRisque: 'Non déclaré',
      profession: 'Étudiante',
    },
    biologie: {
      vih: 'Négatif',
      hbsAg: 'Négatif',
      antiHbc: 'Positif isolé',
      vhc: 'Négatif',
      syphilis: 'Négatif',
      alt: 52,
      hemoglobine: 12.8,
      natRealise: false,
    },
  },
  {
    id: 'cas-3',
    nom: 'Cas 3 — Risque élevé',
    description: 'Le système recommande la quarantaine et des investigations complémentaires.',
    donneur: {
      identifiant: 'DNR-003',
      age: 39,
      sexe: 'Homme',
      region: 'San Pedro',
      typeDonneur: 'Donneur occasionnel',
      nombreDonsAnterieurs: 1,
      dernierDonLabel: 'Il y a 3 ans',
      dernierDonPlus24Mois: true,
      voyageRecent: true,
      voyageRecentDetail: 'Voyage récent (zone non précisée)',
      antecedentMedical: true,
      antecedentMedicalDetail: 'Épisode fébrile récent',
      comportementRisque: 'Oui',
      profession: 'Transporteur',
    },
    biologie: {
      vih: 'Réactif faible',
      hbsAg: 'Négatif',
      antiHbc: 'Positif',
      vhc: 'Négatif',
      syphilis: 'Positif',
      alt: 76,
      hemoglobine: 13.4,
      natRealise: false,
    },
  },
];
